spring:
  application:
    name: service-cuenta-bancaria
  config:    import: optional:configserver:http://localhost:8888  
#  cloud:
 #     config:
  #      import-check:
   #       enabled: false
#  data:
 #   mongodb:
  #    uri: mongodb://localhost:27017/banca_app
    
#config:
 # base.endpoint: http://localhost:8082/api/v1/customers
  
#eureka:
 # client:
  #  serviceUrl.defaultZone: http://localhost:8090/eureka
    